sudo: required

services:  
  - docker

before_install: 
  - docker build -t sobolvitya/docker_aws_tutorial -f Dockerfile.dev .

script:
  - docker run sobolvitya/docker_aws_tutorial npm run test -- --coverage